### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by shilpasr28** [zpz/bigdict#13]
**Test script**

`import logging
import datetime
from sunny.util.bigdict import Bigdict

logger = logging.getLogger(__name__)

def test_bigdict():
    bd = Bigdict.new()
    print(bd)
    i = 0
    while i <= 100_000_000:
        bd[('a', i)] = {'a': 3, 'b': 4}
        i += 1
        if i % 100_000 == 0:
            bd.flush()
            t = datetime.datetime.now()
            logger.info(f'{t} Bigdict size is {len(bd)}')
    bd.destroy()`

**Logs:**

> [32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:26.005034 Bigdict size is 100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:27.043905 Bigdict size is 200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:28.153622 Bigdict size is 300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:29.372022 Bigdict size is 400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:30.632980 Bigdict size is 500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:31.969308 Bigdict size is 600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:33.382391 Bigdict size is 700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:34.881730 Bigdict size is 800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:36.482157 Bigdict size is 900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:38.136476 Bigdict size is 1000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:39.892218 Bigdict size is 1100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:41.703131 Bigdict size is 1200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:43.588578 Bigdict size is 1300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:45.557841 Bigdict size is 1400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:47.626130 Bigdict size is 1500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:49.833410 Bigdict size is 1600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:52.082915 Bigdict size is 1700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:54.439476 Bigdict size is 1800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:56.822857 Bigdict size is 1900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:07:59.306711 Bigdict size is 2000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:01.864641 Bigdict size is 2100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:04.488559 Bigdict size is 2200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:07.401023 Bigdict size is 2300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:10.286687 Bigdict size is 2400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:13.553786 Bigdict size is 2500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:16.764985 Bigdict size is 2600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:24.323700 Bigdict size is 2700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:31.975982 Bigdict size is 2800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:39.596059 Bigdict size is 2900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:08:47.997573 Bigdict size is 3000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:09:04.526543 Bigdict size is 3100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:09:23.125844 Bigdict size is 3200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:09:39.179787 Bigdict size is 3300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:09:52.142926 Bigdict size is 3400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:10:04.304786 Bigdict size is 3500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:10:19.467684 Bigdict size is 3600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:10:34.420576 Bigdict size is 3700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:10:48.165419 Bigdict size is 3800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:11:05.156382 Bigdict size is 3900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:11:22.521542 Bigdict size is 4000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:11:40.156876 Bigdict size is 4100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:11:58.366535 Bigdict size is 4200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:12:19.471680 Bigdict size is 4300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:12:39.823267 Bigdict size is 4400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:13:01.519611 Bigdict size is 4500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:13:23.093099 Bigdict size is 4600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:13:45.835237 Bigdict size is 4700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:14:05.655938 Bigdict size is 4800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:14:26.891879 Bigdict size is 4900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:14:47.076791 Bigdict size is 5000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:15:08.877333 Bigdict size is 5100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:15:32.106174 Bigdict size is 5200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:15:56.329499 Bigdict size is 5300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:16:22.830668 Bigdict size is 5400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:16:46.860600 Bigdict size is 5500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:17:12.400465 Bigdict size is 5600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:17:33.854909 Bigdict size is 5700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:18:05.522695 Bigdict size is 5800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:18:31.356645 Bigdict size is 5900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:18:57.071237 Bigdict size is 6000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:19:28.230323 Bigdict size is 6100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:19:58.433670 Bigdict size is 6200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:20:27.578002 Bigdict size is 6300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:20:55.052075 Bigdict size is 6400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:21:23.882480 Bigdict size is 6500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:21:48.820294 Bigdict size is 6600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:22:16.095581 Bigdict size is 6700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:22:46.574693 Bigdict size is 6800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:23:20.038857 Bigdict size is 6900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:23:52.768650 Bigdict size is 7000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:24:24.817752 Bigdict size is 7100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:24:55.329479 Bigdict size is 7200000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:25:27.937510 Bigdict size is 7300000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:26:03.647051 Bigdict size is 7400000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:26:35.149231 Bigdict size is 7500000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:27:09.633116 Bigdict size is 7600000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:27:44.624899 Bigdict size is 7700000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:28:18.177528 Bigdict size is 7800000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:28:52.517088 Bigdict size is 7900000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:29:32.955431 Bigdict size is 8000000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:30:26.998225 Bigdict size is 8100000
[32mINFO    [0m test_bigdict_speed:test_bigdict_speed.py:19 2022-08-23 15:31:07.710588 Bigdict size is 8200000

I used this code to test bigdict 22.5.29 and bigdict 21.4.11: https://gecgithub01.walmart.com/Qarth/sunny/blob/038eee4cf9bda65a70f6a2ae66a2a99b11372dcf/tests/util/test_speed_biglist_and_bigdict.py#L10
As you see in the logs, I am logging after updating 100k items in the dict
Initially this is taking ~1s, later on when the size of the bigdict is huge, the updating time ~1min. The time is gradually increasing.
When I checked "docker stats", MEM% at 10k items was 2442MB and at 1M items it had increased to 1GB. Memory is also definitely increasing

**Comment by zpz** [comment]
The speed degradation is due to your call to `flush()`. `flush()` does some compaction (think re-org for optimal size, remove redundancy, etc), and is supposed to be called only when you're done with a session.

Without the calls to `flush`, my test shows the time it takes to insert 100_000 items starts around 1 sec, and rather quickly increased to 1.3x sec and fluctuates. When the total is around 25_000_000, it's fluctuating roughly between 1.6-2.6 sec. When the total is 56_000_000 (when I stopped), it's fluctuating between 1.6-2.7 sec, occasionally as high as  3.2 sec. I suppose this is expected behavior.

The Docker mem usage on my machine started at 900 MB and gradually increased. When the total is 25_000_000, mem usage is around 1.6 GB; at 50_000_000,  mem usage is 1.7 GB; it does increase gradually. When I stopped the test at 65_000_000, the mem is 1.8 GB. I believe this is just normal RocksDB memory consumption. `Bigdict` is a very very thin wrapper on RocksDB (or more precisely, the third-party Python client to RocksDB). There's very little room for bugs in `Bigdict` itself.
